### ISSUE TITLE
Using the `vsock-proxy` to other addresses

### ISSUE THREAD

**Issue by pedroprates** [richardfan1126/nitro-enclave-python-demo#2]
Hello @richardfan1126! 

First of all, congratulations on this repository! It is very helpful to understand how nitro enclaves work, and especially using a Python script. 

I have a question though, I am trying to perform an API call from inside the enclave, I am retrieving some sensitive data and would like to process it from inside the enclave. I was thinking about using the `vsock-proxy` tool to redirect the traffic from inside the enclave to this API, which is not from AWS. Although I am not sure if this is possible, when I try to do this, EC2 tells me that there was an error checking the `allowlist`, but I do not know how to add this new address to the allowlist. 

Do you have anything in mind that could help me on this?

Thank you!

**Comment by richardfan1126** [comment]
@pedroprates 

This issue is related to `vsock-proxy` configuration

You need to specify the configuration to use when running `vsock-proxy`. Please check this: https://github.com/aws/aws-nitro-enclaves-cli/blob/main/vsock_proxy/README.md#flags-and-options

You can create your own configuration by referencing the default one: https://github.com/aws/aws-nitro-enclaves-cli/blob/main/vsock_proxy/configs/vsock-proxy.yaml
