### ISSUE TITLE
How to trust the SecretStore ?

### ISSUE THREAD

**Issue by msnitish** [richardfan1126/nitro-enclave-python-demo#8]
I have checked the attestation verifier project here. Thank you very much for the architecture diagram too.
I understand that using the attestation document generated by the hypervisor for the requesting enclave can be used to establish the identity of an enclave for us to trust it.
But how can we make sure that the enclave sends data only to the trusted clients  ?
Should a remote client (in some foreign instance) provide their own version of attestation/some identity to the enclave so that it will trust this remote client ?

**Comment by richardfan1126** [comment]
@msnitish 

Short answer, you should implement your own authentication method to verify the enclave's client. Attestation is to verify the enclave's identity, not its client.

---

For a more detailed answer, you need to first understand what issue Nitro Enclaves is going to solve.

Nitro Enclaves is a confidential computing environment, it is designed to protect **data-in-use**.

Take OAuth as an example. Let's say I am the **Service Provider**, I want to use a 3-legged OAuth to access my clients' identity and information (Let's say from Facebook).

To do so, I need to create an OAuth app on Facebook and get my **Client Secret**.

The Client Secret is the most confidential data I want to protect, so I will store it inside my **Secret Store**.

But on other hand, I also need to use it to process the OAuth authentication process ([Authorization Code Exchange](https://www.oauth.com/oauth2-servers/pkce/authorization-code-exchange/)). My secret store is a database, it cannot process the authentication logic, so in some way, my Client Secret still needs to go out of my Secret Store to a processor (e.g. VM, container, etc.). But how can I guarantee that my Client Secret will remain confidential in that processor (e.g. No one can log in to the container and view the Client Secret)?

This is where Nitro Enclaves comes.

![](https://i.imgur.com/BTphSFA.jpg)

This diagram shows that by using Nitro Enclaves and attestation, we can build a perimeter that protects the Client Secret.

The Secret Store know it is sending the Client Secret to a genuine Nitro Enclaves by verifying the request's attestation document. The Nitro Enclaves ensure the data inside cannot be accessed. So we can safely say the Client Secret will not go out of the Confidential Perimeter.

Is the client genuine? I don't care (at least not Nitro Enclave's concern). The client will provide his/her Facebook username and password, and receive the response of login success/failure. As long as he/she cannot retrieve the Client Secret, I don't care who is he/she.

---

You may ask, what if I fake the Nitro Enclaves by pretending to be the real Secret Store? Can I attack the Nitro Enclaves by this path? The answer is also No.

![](https://i.imgur.com/Mfx5xdm.jpg)

Consider this scenario: A hacker somehow fakes the Nitro Enclaves to make it thinks he is the real Secret Store, and provide it with a fake Client Secret.

The Nitro Enclaves use this fake Client Secret to process the OAuth authentication and of course, the login will fail because Facebook recognizes it is a wrong secret.

It's not a big deal (of course the hacker successfully take down the login function, but again it's not Nitro Enclaves' concern) because the hacker still can't get my real Client Secret. The hacker still cannot break into the Confidential Perimeter.

---

Remember, Nitro Enclaves is to protect confidential data by providing a safe computing environment. The attestation document is to help protect the **data**, not the enclave.

Although your concern may be valid in some cases. But more probably, it's because you are using Nitro Enclaves in the wrong way. Maybe you treat Nitro Enclaves as a data store. Maybe your architecture is moving the confidential data too far outside the perimeter (e.g. forward the Client Secret to the client). Those use cases are not the purpose of confidential computing.

**Comment by nitish-at** [comment]
@richardfan1126  
Thank you for the clear explanation with images. I had a similar thought about attestation and it got confirmed firmly now.

**About my actual use case:**
I would like to know how useful, feasible it is to create a multiparty computation system using Nitro Enclaves where multiple clients send data to a common(central) environment having Nitro Enclave for processing the data by applications running in it and clients can receive the final result after all this processing.

**Comment by msnitish** [comment]
@richardfan1126
Thank you for the clear explanation with images. I had a similar thought about attestation and it got confirmed firmly now.
About my actual use case:
I would like to know how useful, feasible it is to create a multiparty computation system using Nitro Enclaves where multiple clients send data to a common(central) environment having Nitro Enclave for processing the data by applications running in it and clients can receive the final result after all this processing.

**Comment by richardfan1126** [comment]
@msnitish 

There are many useful use-cases. For example machine learning.

The service provider, who develop the AI model, doesn't want to provide their model to their customers. The customers also don't want to provide their data. So where should the inference take place? Nitro Enclaves can be one of the solutions.

But to achieve the trust relationship, the customers need to assess how AWS can guarantee their data cannot be accessed from the enclave (even the account owner, which is the service provider, can not access it).

But unfortunately, I still can't find any formal documentation specifically on Nitro Enclaves, which can fulfil the audit requirement.
